name: loader_search_bar
description: App bar and search widget integrated.
version: 0.0.2+2
author: Tomasz Wyrowinski <tomwyr@hotmail.com>
homepage: https://github.com/tomwyr/loader-search-bar

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
